---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: external-dns-errors
  namespace: kube-system
  labels:
    prometheus: cloud-platform
spec:
  groups:
  - name: external-dns
    rules:
    - alert: ErrorsInExternalDNS
      expr: sum(increase(external_dns_registry_errors_total[2h])) > 5
      for: 5m
      labels:
        severity: warning
      annotations:
        message: Errors found in external-dns service; This may be caused by an ingress rule lacking a weight annotation.
        runbook_url: https://runbooks.cloud-platform.service.justice.gov.uk/external-dns-error.html#how-to-investigate-external-dns-errors
